server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/infosec_db
    username: alinaarmut
    password: " "
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: very_long_random_secret_change_in_prod_here_!@#123
  expiration-ms: 3600000  # 1 hour
